# Generated by Django 6.0.2 on 2026-02-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.dynamicform'),
        ),
    ]
